### ISSUE TITLE
Banner Problem

### ISSUE THREAD

**Issue by arundhishaan15** [arundhishaan15/guess-the-number-game#4]
- [x] Don't add two banners. Delete one. Have only one banner!

- [x] Have the title of the banner - Guess the Number

If you like you can work on the font style and size of the banner to look dashing. Maybe UI Designers would use Photoshop to create their banners. They may also use canva.com. Overall design looks good.

_Originally posted by @arundhishaan15 in https://github.com/arundhishaan15/guess-the-number-game/pull/3/review_comment/create_

**Comment by Nidhushan** [comment]
completed
