### ISSUE TITLE
Title problem

### ISSUE THREAD

**Issue by arundhishaan15** [arundhishaan15/guess-the-number-game#5]
- [ ] Change the title: "Type your guess here:" Because you already have a placeholder that says "What's your guess?" Change it to 1...100 or 1.2.3.4.5 or 1~2~~100 something simple and in big styled fonts like the one before.

_Originally posted by @arundhishaan15 in https://github.com/arundhishaan15/guess-the-number-game/pull/3/review_comment/create_

**Comment by Nidhushan** [comment]
done
